{{- if eq .Values.deployment.target "openshift" }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: showroom
  namespace: {{.Values.deployment.namespace}}
spec:
  port:
    targetPort: 8000
  to:
    kind: Service
    name: showroom
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}