{{- if eq .Values.deployment.target "openshift" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.deployment.serviceAccountName}}
  namespace: {{.Values.deployment.namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-configmaps
  namespace: {{.Values.deployment.namespace}}
rules:
  - verbs:
      - watch
      - get
      - list
    apiGroups:
      - ""
    resources:
      - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-config-maps-to-sa
  namespace: {{.Values.deployment.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-configmaps
subjects:
  - kind: ServiceAccount
    name: {{.Values.deployment.serviceAccountName}}
    namespace: {{.Values.deployment.namespace}}
{{- end }}
