---
deployment:
  target: podman
  hostname: showroom-example.com:8443

services:
  content:
    repoUrl: https://github.com/rhpds/showroom_template_default.git
    data:
      lab_name: All new dynamic showroom layouts!!!!

  ttyd:
    command:
    - ssh
    - -o
    - "StrictHostKeyChecking no"
    - -i
    - /.ssh/id
    - lab-user@localhost
    - -p 2222

  # openssh is enabled here for the example, giving ttyd an ssh server to connect to
  openssh:
    enabled: true
    user: lab-user