---
deployment:
  target: openshift
  hostname: showroom.apps.cluster-{{GUID}}.{{GUID}}.{{SANDBOX}}.opentlc.com

#############################################################
# Indiviual service configuration
services:
  content:
    enable: true
    repoUrl: https://github.com/rhpds/showroom_template_default.git
    data:
      lab_name: All new dynamic showroom layouts!

  helloworld:
    enable: true

  terminal:
    enable: true
    command: top

  terminal2:
    enable: true
    host: bastion.{{GUID}}.{{SANDBOX}}.opentlc.com
    user: lab-user
    pass: {{PASSWORD}}
    sshMethod: password
    terminal_command: top

  terminal3:
    enable: true
    host: bastion.{{GUID}}.{{SANDBOX}}.opentlc.com
    user: lab-user
    pass: {{PASSWORD}}
    sshMethod: password

#############################################################
# Layout configuration
layout:
  columns:
    left:
      service: content
      width: 40
    right:
      width: 60
      tabs:
      - name: Terminals
        stack:
          top:
            service: terminal
            height: 30
          middle:
            service: terminal2
            height: 30
          bottom:
            service: terminal3
            height: 40
      - name: Documentation
        url: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/about/welcome-index
      - name: Stack
        stack:
          top:
            service: helloworld
            height: 40
          bottom:
            url: https://en.wikipedia.org/wiki/Red_Hat
            height: 60
