---
deployment:
  target: openshift
  hostname: showroom.apps.cluster-{{GUID}}.{{GUID}}.{{SANDBOX}}.opentlc.com

infrastructure:
  traefik:
    dashboard:
      enabled: true

#############################################################
# Indiviual service configuration
services:
  content:
    enabled: true
    repoUrl: https://github.com/rhpds/showroom_template_default.git
    data:
      lab_name: All new dynamic showroom layouts!

  helloworld:
    enabled: true

  terminal:
    enabled: true
    host: bastion.{{GUID}}.{{SANDBOX}}.opentlc.com
    user: lab-user
    pass: {{PASSWORD}}
    sshMethod: password

  terminal2:
    enabled: true
    host: bastion.{{GUID}}.{{SANDBOX}}.opentlc.com
    user: lab-user
    pass: {{PASSWORD}}
    sshMethod: password

  ttyd:
    enabled: true
    command:
    - sshpass
    - -p
    - {{PASSWORD}}
    - ssh
    - -o
    - "StrictHostKeyChecking no"
    - lab-user@bastion.{{GUID}}.{{SANDBOX}}.opentlc.com

#############################################################
# Layout configuration
layout:
  columns:
    left:
      service: content
      width: 40
    right:
      width: 60
      tabs:
      - name: Terminals
        stack:
          top:
            service: terminal
            height: 30
          middle:
            service: terminal2
            height: 30
          bottom:
            service: ttyd
            height: 40
      - name: Documentation
        url: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/about/welcome-index
      - name: Stack
        stack:
          top:
            service: helloworld
            height: 34
          bottom:
            url: https://en.wikipedia.org/wiki/Red_Hat
            height: 66
      - name: Traefik Dashboard
        service: traefikDashboard