---
deployment:
  target: podman
  hostname: showroom-example.com:8443

infrastructure:
  traefik:
    dashboard:
      enabled: true

#############################################################
# Indiviual service configuration
services:
  content:
    enabled: true
    repoUrl: https://github.com/rhpds/showroom_template_default.git
    data:
      lab_name: All new dynamic showroom layouts!

  helloworld:
    enabled: true

  terminal:
    enabled: true
    host: localhost
    port: 2222
    user: lab-user
    sshMethod: publickey

  terminal2:
    enabled: true
    host: localhost
    port: 2222
    user: lab-user
    sshMethod: password
    pass: Password1

  ttyd:
    enabled: true
    command:
    - ssh
    - -o
    - "StrictHostKeyChecking no"
    - -i
    - /.ssh/id
    - lab-user@localhost
    - -p 2222

  openssh:
    enabled: true
    user: lab-user
    pass: Password1
    sshKeyDir: files/ssh

#############################################################
# Layout configuration
layout:
  columns:
    left:
      service: content
      width: 40
    right:
      width: 60
      tabs:
      - name: Terminals
        stack:
          top:
            service: terminal
            height: 30
          middle:
            service: terminal2
            height: 30
          bottom:
            service: ttyd
            height: 40
      - name: Documentation
        url: https://docs.redhat.com/en/documentation/openshift_container_platform/4.18/html/about/welcome-index
      - name: Stack
        stack:
          top:
            service: helloworld
            height: 34
          bottom:
            url: https://en.wikipedia.org/wiki/Red_Hat
            height: 66
      - name: Traefik Dashboard
        service: traefikDashboard